import type { NewsDetails } from '../model'

export const emptyArticle: NewsDetails = {
  id: '0',
  date: '',
  en: {
    title: '',
    shortDesc: '',
    fullDesc: ''
  },
  ru: {
    title: '',
    shortDesc: '',
    fullDesc: ''
  },
  kz: {
    title: '',
    shortDesc: '',
    fullDesc: ''
  },
  img: ''
}

export const newsCollection: NewsDetails[] = [
  {
    id: '1',
    date: '15.06.2024',
    ru: {
      title: 'Итальянская керамика',
      shortDesc:
        'Итальянская кухня известна по всему миру благодаря знаменитым блюдам, таким как пицца, спагетти и ньокки. Но не менее важной частью итальянской культуры является посуда. Итальянцы умеют не только готовить вкусные блюда, но и подавать их в красивой посуде.',
      fullDesc:
        'Итальянская кухня известна по всему миру благодаря знаменитым блюдам, таким как пицца, спагетти и ньокки. Но не менее важной частью итальянской культуры является посуда. Итальянцы умеют не только готовить вкусные блюда, но и подавать их в красивой посуде. Итальянская керамическая посуда известна своим утончённым дизайном, качеством и долговечностью. Она отражает богатую культуру и историю Италии, передаваясь из поколения в поколение. Такая посуда не стареет, её можно ежедневно мыть и дезинфицировать, при этом она сохраняет свои качества и внешний вид. Украшена может быть орнаментами и декорами, такими как изображения фруктов, овощей, цветов и других элементов природы. Несмотря на кажущуюся хрупкость, итальянская керамическая посуда предназначена для интенсивного использования. Она соответствует строгим европейским стандартам безопасности для материалов, контактирующих с пищей. Гладкие, непористые поверхности не впитывают жиры, запахи и бактерии, что делает её безопасной для здоровья. Керамическая посуда из Италии является выражением культурных традиций страны. Мастерство итальянских гончаров и художников передаётся из поколения в поколение, что гарантирует высокие стандарты качества и эстетики. Каждое изделие, будь то тарелка, чашка или ваза, несёт в себе уникальный дизайн и высокое качество исполнения. Бренд "Made in Italy" объединяет традиционные ценности, инновации, стиль и долговечность керамических изделий. Многие города Италии, такие как Дерута, Фаенца и Сиена, известны своими уникальными стилями керамики. Дерута славится своими красочными узорами и сложными мотивами, в то время как Фаенца известна своими художественными инновациями и изысканными техниками. Эти региональные особенности добавляют итальянской керамике разнообразие и уникальность, делая её желанной среди коллекционеров и ценителей искусства. Выбирая итальянскую керамическую посуду, вы делаете выбор в пользу качества, красоты и долговечности. Это идеальное решение для тех, кто хочет внести частичку итальянского тепла и уюта в свой дом, ресторан или бар. Итальянская керамика — это не просто посуда, это искусство, которое проходит испытание временем и приносит радость каждому своему владельцу.'
    },
    en: {
      title: 'Italian ceramics',
      shortDesc:
        'Italian cuisine is known throughout the world thanks to famous dishes such as pizza, spaghetti and gnocchi. But an equally important part of Italian culture is tableware. Italians know how to not only cook delicious dishes, but also serve them in beautiful dishes.',
      fullDesc:
        'Italian cuisine is known throughout the world thanks to famous dishes such as pizza, spaghetti and gnocchi. But an equally important part of Italian culture is tableware. Italians know how to not only cook delicious dishes, but also serve them in beautiful dishes. Italian ceramic tableware is known for its sophisticated design, quality and durability. It reflects the rich culture and history of Italy, passed down from generation to generation. Such dishes do not age, they can be washed and disinfected daily, while they retain their quality and appearance. It can be decorated with ornaments and decors, such as images of fruits, vegetables, flowers and other elements of nature. Despite their apparent fragility, Italian ceramic tableware is designed for intensive use. It meets strict European safety standards for materials in contact with food. Smooth, non-porous surfaces do not absorb fats, odors and bacteria, which makes it safe for health. Ceramic tableware from Italy is an expression of the country’s cultural traditions. The skill of Italian potters and artists is passed down from generation to generation, guaranteeing high standards of quality and aesthetics. Each product, be it a plate, cup or vase, has a unique design and high quality workmanship. The "Made in Italy" brand combines traditional values, innovation, style and durability of ceramic products. Many cities in Italy, such as Deruta, Faenza and Siena, are known for their unique styles of ceramics. Deruta is famous for its colorful patterns and intricate motifs, while Faenza is known for its artistic innovation and refined techniques. These regional characteristics add variety and uniqueness to Italian ceramics, making them desirable among collectors and art lovers. When choosing Italian ceramic tableware, you are making a choice in favor of quality, beauty and durability. This is the ideal solution for those who want to bring a piece of Italian warmth and comfort into their home, restaurant or bar. Italian ceramics is not just dishes, it is an art that stands the test of time and brings joy to each of its owners.'
    },
    kz: {
      title: 'Италия керамикасы',
      shortDesc:
        'Итальяндық асхана пицца, спагетти және нокки сияқты әйгілі тағамдардың арқасында бүкіл әлемге танымал. Бірақ итальяндық мәдениеттің бірдей маңызды бөлігі - ыдыс-аяқ. Итальяндықтар дәмді тағамдарды дайындауды ғана емес, сонымен қатар оларды әдемі тағамдармен ұсынуды біледі.',
      fullDesc:
        'Итальяндық асхана пицца, спагетти және нокки сияқты әйгілі тағамдардың арқасында бүкіл әлемге танымал. Бірақ итальяндық мәдениеттің бірдей маңызды бөлігі - ыдыс-аяқ. Итальяндықтар дәмді тағамдарды дайындауды ғана емес, сонымен қатар оларды әдемі тағамдармен ұсынуды біледі. Итальяндық керамикалық ыдыс-аяқ өзінің күрделі дизайнымен, сапасымен және ұзақ мерзімділігімен танымал. Ол Италияның ұрпақтан-ұрпаққа жалғасып келе жатқан бай мәдениеті мен тарихын көрсетеді. Мұндай ыдыс-аяқтар ескірмейді, олардың сапасы мен сыртқы түрін сақтай отырып, күнделікті жууға және дезинфекциялауға болады. Оны әшекейлермен және декорлармен безендіруге болады, мысалы, жемістер, көкөністер, гүлдер және табиғаттың басқа элементтерінің суреттерімен. Көрінетін нәзіктігіне қарамастан, итальяндық керамикалық ыдыс қарқынды қолдануға арналған. Ол азық-түлікпен жанасатын материалдар үшін қатаң еуропалық қауіпсіздік стандарттарына сәйкес келеді. Тегіс, кеуекті емес беттер майларды, иістерді және бактерияларды сіңірмейді, бұл оны денсаулық үшін қауіпсіз етеді. Италиядан келген керамикалық ыдыс – бұл елдің мәдени дәстүрінің көрінісі. Итальяндық құмырашылар мен суретшілердің шеберлігі ұрпақтан ұрпаққа беріліп, сапа мен эстетиканың жоғары стандарттарына кепілдік береді. Әрбір бұйым, мейлі ол тәрелке, кесе немесе ваза болсын, бірегей дизайн және жоғары сапалы жұмыс. «Made in Italy» бренді керамикалық бұйымдардың дәстүрлі құндылықтарын, инновацияларын, стилі мен беріктігін біріктіреді. Дерута, Фаенца және Сиена сияқты Италияның көптеген қалалары керамиканың ерекше стильдерімен танымал. Дерута өзінің түрлі-түсті өрнектерімен және күрделі мотивтерімен танымал, ал Фаенза өзінің көркемдік инновациялары мен талғампаз әдістерімен танымал. Бұл аймақтық сипаттамалар итальяндық керамикаға әртүрлілік пен бірегейлік қосады, бұл оларды коллекционерлер мен өнер сүйер қауым арасында қажет етеді. Итальяндық керамикалық ыдыстарды таңдағанда, сіз сапа, сұлулық және ұзақ мерзімділік пайдасына таңдау жасайсыз. Бұл үйіне, мейрамханасына немесе барына итальяндық жылу мен жайлылықтың бір бөлігін әкелгісі келетіндер үшін тамаша шешім. Итальяндық керамика жай ғана ыдыс емес, ол уақыт сынынан сүрінбей өтіп, әрбір иесіне қуаныш сыйлайтын өнер.'
    },
    img: 'news-1.jpg'
  },
  {
    id: '2',
    date: '20.04.2024',
    ru: {
      title: 'Шарфы и пледы Elvangь',
      shortDesc:
        'Датский бренд Elvang представляет собой производителя высококачественных шарфов и пледов, которые объединяют в себе комфорт, элегантность и превосходное качество. Их изделия изготавливаются из уникального материала — шерсти альпака, которая обладает рядом удивительных свойств.',
      fullDesc:
        'Датский бренд Elvang представляет собой производителя высококачественных шарфов и пледов, которые объединяют в себе комфорт, элегантность и превосходное качество. Их изделия изготавливаются из уникального материала — шерсти альпака, которая обладает рядом удивительных свойств. История бренда началась в 2003 году, когда супружеская пара Тина и Лассе, путешествуя по Перу, впервые познакомилась с изделиями из шерсти альпака. Вдохновленные теплом и мягкостью этих изделий, они решили предложить их на европейском рынке. Основным материалом для изготовления пледов и шарфов является шерсть альпака, которая обладает рядом уникальных качеств. Ее волокна очень тонкие и мягкие, именно они придают изделиям невероятную мягкость и комфорт. Благодаря отсутствию ланолина, шерсть альпака гипоаллергенна, что делает ее безопасной для аллергиков. Полые внутренние волокна обеспечивают повышенную теплоизоляцию, делая изделия теплыми и легкими. Кроме того, шерсть альпака более устойчива к износу по сравнению с овечьей шерстью и не скатывается со временем. Ее поверхность гладкая, что предотвращает образование катышков.  Преимущества продукции Elvang не ограничиваются только качеством материалов. Их изделия также отличаются изысканным дизайном и стильными узорами. Каждое изделие — это произведение искусства, выражающее внимание к деталям и безупречный вкус. Бренд предлагает разнообразные коллекции, включая Classic, Modern, Luxe и Eco, каждая из которых имеет свой неповторимый стиль и характер. Pазличные коллекции Elvang предоставляют широкий выбор для любого вкуса и предпочтений. Их продукция не только уютна и комфортна для использования дома, но также может служить в качестве превосходного корпоративного подарка. Персонализация изделий с логотипом компании делает их идеальным способом подчеркнуть важность вашего бренда и создать благоприятное впечатление на клиентов и партнеров. Кроме того, Elvang уделяет особое внимание социальной ответственности и справедливой торговле. Бренд поддерживает прямые поставки шерсти альпака от перуанских производителей, обеспечивая справедливую оплату труда скотоводов и улучшая их условия жизни. Эта поддержка обеспечивает рабочие места и стабильный доход для местного населения. В заключение, стоит подчеркнуть, что пледы и шарфы от Elvang представляют собой не только элегантные аксессуары, но и воплощение баланса между стилем и заботой. Их особенные материалы и дизайн являются проявлением внимания к мельчайшим деталям и прекрасному вкусу создателей, а усилия по соблюдению принципов социальной ответственности делают бренд еще более привлекательным для ценителей качественных и экологически чистых изделий.'
    },
    en: {
      title: 'Elvangs’ scarves and blankets ',
      shortDesc:
        'Danish brand Elvang is a manufacturer of high-quality scarves and blankets that combine comfort, elegance and superior quality.',
      fullDesc:
        'Danish brand Elvang is a manufacturer of high-quality scarves and blankets that combine comfort, elegance and superior quality. Their products are made from a unique material - alpaca wool, which has a number of amazing properties. The history of the brand began in 2003, when the married couple Tina and Lasse, while traveling in Peru, first became acquainted with products made from alpaca wool. Inspired by the warmth and softness of these products, they decided to offer them on the European market. The main material for making blankets and scarves is alpaca wool, which has a number of unique qualities. Its fibers are very thin and soft, they give the products incredible softness and comfort. Due to the absence of lanolin, alpaca wool is hypoallergenic, making it safe for allergy sufferers. Hollow inner fibers provide increased thermal insulation, making products warm and lightweight. In addition, alpaca wool is more resistant to wear and tear than sheep wool and does not pill over time. Its surface is smooth, which prevents the formation of pellets. The advantages of Elvang products are not limited to the quality of materials. Their products also feature exquisite designs and stylish patterns. Each product is a work of art, expressing attention to detail and impeccable taste. The brand offers a variety of collections including Classic, Modern, Luxe and Eco, each with its own unique style and character. Elvang	’s various collections provide a wide choice for every taste and preference. Their products are not only cozy and comfortable to use at home, but also make excellent corporate gifts. Personalizing products with a company logo makes them an ideal way to highlight the importance of your brand and create a positive impression on customers and partners. In addition, Elvang places special emphasis on social responsibility and fair trade. The brand supports direct sourcing of alpaca wool from Peruvian producers, ensuring fair wages for herders and improving their living conditions. This support provides jobs and stable income for the local population. In conclusion, it is worth emphasizing that Elvang blankets and scarves are not only elegant accessories, but also the embodiment of the balance between style and care. Their distinctive materials and designs reflect the attention to detail and excellent taste of their creators, while their efforts to comply with the principles of social responsibility make the brand even more attractive to connoisseurs of quality and environmentally friendly products.'
    },
    kz: {
      title: 'Elvang oрамал мен көрпелері',
      shortDesc:
        'Даниялық Elvang бренді жайлылық, талғампаздық пен ерекше сапаны біріктіретін жоғары сапалы шарфтар мен көрпелерді шығарумен танымал. Брендтің өнімдері бірегей материалдан - көптеген таңғажайып қасиеттерге ие альпака жүнінен жасалған.',
      fullDesc:
        'Даниялық Elvang бренді жайлылық, талғампаздық пен ерекше сапаны біріктіретін жоғары сапалы шарфтар мен көрпелерді шығарумен танымал. Брендтің өнімдері бірегей материалдан - көптеген таңғажайып қасиеттерге ие альпака жүнінен жасалған. Эльвангтың тарихы 2003 жылы, жұп Тина мен Лассе Перуде саяхаттаған кезде альпака жүнінен жасалған бұйымдармен алғаш танысқан кезде басталды. Бұл өнімдердің жылуы мен жұмсақтығынан шабыттанған олар бұл өнімдерді Еуропа нарығына шығаруға шешім қабылдады. Elvang өнімдерінің негізі болып табылатын альпака жүні бірегей қасиеттерге ие - жұқа және жұмсақ талшықтар өнімдерге керемет жұмсақтық пен жайлылық береді, ал ланолиннің болмауына байланысты жүн гипоаллергенді болып табылады, бұл оны аллергиямен ауыратындар үшін қауіпсіз етеді. Қуыс ішкі талшықтар тамаша жылу оқшаулауын қамтамасыз етеді, өнімдерге жылы және жеңілдік сыйлайды. Сонымен қатар, альпака жүні қой жүніне қарағанда тозуға төзімді және оның тегіс беті уақыт өте келе қабыршақтануды болдырмайды. Жоғары сапалы материалдардан басқа, Elvang өнімдері талғампаз дизайнымен және сәнді үлгілерімен ерекшеленеді. Әрбір бұйым егжей-тегжейге назар аударатын және мінсіз талғамды білдіретін өнер туындысы. Бренд Classic, Modern, Luxe және Eco сияқты әртүрлі топтамаларды ұсынады, олардың әрқайсысының өзіндік ерекше стилі мен сипаты бар. Elvang топтамалары кез келген дәм мен қалау үшін кең таңдауды ұсынады. Олардың өнімдері үйге ыңғайлы, сонымен қатар корпоративтік сыйлықтар үшін де өте қолайлы. Компанияның логотипі бар өнімдер брендіңіздің маңыздылығын көрсетудің және тұтынушылар мен серіктестерге жағымды әсер қалдырудың тамаша тәсілінің бірі. Эльванг сонымен қатар әлеуметтік жауапкершілік пен әділ саудаға қатты мән береді. Бренд альпака жүнін Перу өндірушілерінен тікелей сатып алуды қолдайды, малшылардың әділ жалақысын қамтамасыз етеді және олардың өмір сүру жағдайларын жақсартады. Бұл көмек жұмыс орындарын ашып, жергілікті халықты тұрақты табыспен қамтамасыз етуде. Қорытындылай келе, Elvang көрпелері мен шарфтары тек талғампаз аксессуарлар ғана емес, сонымен қатар стиль мен күтім арасындағы тепе-теңдікті бейнелейтінін атап өткен жөн. Бірегей материалдар мен дизайн жасаушылардың егжей-тегжейлері мен талғампаз талғамына назар аударады, ал әлеуметтік жауапкершілік қағидаттарына адалдық брендті жоғары сапалы және экологиялық таза өнімдерді білушілер үшін одан да тартымды етеді.'
    },
    img: 'news-2.jpg'
  },
  {
    id: '3',
    date: '20.03.2024',
    ru: {
      title: 'Диван-кровать',
      shortDesc:
        'Любая домашняя мебель должна быть удобной, функциональной и эстетически приятной. В зависимости от стиля дома, она также должна отражать тему или дизайн пространства. Практичное и удобное дополнение к любому дому - большому или маленькому - диван-кровати. Они идеально подходят для гостей, которые остаются на ночь, уменьшая потребность в дополнительной кровати или запасной спальне.',
      fullDesc:
        'Любая домашняя мебель должна быть удобной, функциональной и эстетически приятной. В зависимости от стиля дома, она также должна отражать тему или дизайн пространства. Практичное и удобное дополнение к любому дому - большому или маленькому - диван-кровати. Они идеально подходят для гостей, которые остаются на ночь, уменьшая потребность в дополнительной кровати или запасной спальне. В нашем салоне представлены диваны-кровати испанского бренда. Их отличительная особенность в безупречном качестве и отличном дизайне. Ведь механизм открывания и закрытия дивана-кровати имеет значение, потому что именно он определяет, насколько легко превратить диван в кровать и обратно в диван. Для небольших помещений у нас есть ряд одноместных и двухместных диванов-кроватей, которые занимают минимум места в гостиной и при необходимости трансформируются в удобные односпальные или двуспальные кровати. Для больших семей можем предложить трёхместные диваны. Во многих домах диваны-кровати используются в качестве основной кровати, а не в качестве запасной. Это характерно для квартир-студий, которые превращаются из гостиной днём в спальню ночью. Таким образом, диван-кровать - это стоящая инвестиция, которая позволит сэкономить деньги в долгосрочной перспективе, ведь вам не нужно будет покупать другую мебель для сна.'
    },
    en: {
      title: 'Sofa-bed',
      shortDesc:
        'Any home furniture should be comfortable, functional and aesthetically pleasing. Depending on the style of the home, it should also reflect the theme or design of the space. A practical and comfortable addition to any home - large or small - sofa beds. They are ideal for guests staying overnight, reducing the need for an extra bed or spare bedroom.',
      fullDesc:
        'Any home furniture should be comfortable, functional and aesthetically pleasing. Depending on the style of the home, it should also reflect the theme or design of the space. A practical and comfortable addition to any home - large or small - sofa beds. They are ideal for guests staying overnight, reducing the need for an extra bed or spare bedroom. Our showroom features sofa beds from a Spanish brand. Their distinctive feature is impeccable quality and excellent design. After all, the mechanism for opening and closing a sofa bed matters because it determines how easy it is to turn the sofa into a bed and back into a sofa. For smaller spaces, we have a range of single and double sofa beds that take up minimal space in the living room and can be converted into comfortable single or double beds if required. For large families we can offer three-seater sofas. In many homes, sofa beds are used as the main bed rather than as a spare bed. This is typical for studio apartments, which transform from a living room during the day to a bedroom at night. Thus, a sofa bed is a worthwhile investment that will save you money in the long run because you won’t need to buy other furniture to sleep on.'
    },
    kz: {
      title: 'Диван-төсек',
      shortDesc:
        'Үй жиһазы ыңғайлы, функционалды және эстетикалық жағынан жағымды болуы керек. Үйдің стиліне байланысты ол сонымен қатар кеңістіктің тақырыбын немесе дизайнын көрсетуі керек. Кез-келген үйге практикалық және ыңғайлы қосымша - үлкен немесе кіші - диван-төсек. Олар түнге қалатын қонақтар үшін өте ыңғайлы, қосымша төсекке немесе қосалқы бөлмеге қажеттілікті азайтады.',
      fullDesc:
        'Үй жиһазы ыңғайлы, функционалды және эстетикалық жағынан жағымды болуы керек. Үйдің стиліне байланысты ол сонымен қатар кеңістіктің тақырыбын немесе дизайнын көрсетуі керек. Кез-келген үйге практикалық және ыңғайлы қосымша - үлкен немесе кіші - диван-төсек. Олар түнге қалатын қонақтар үшін өте ыңғайлы, қосымша төсекке немесе қосалқы бөлмеге қажеттілікті азайтады. Біздің салонда испан брендінің диван-төсектері ұсынылған. Олардың ерекшілігі - жағары сапа және керемет дизайны. Өйткені, диваннің ашу және жабу механизмі диванды төсекке және қайта диванға айналдыру қаншалықты оңай екенін анықтайды. Кішкентай үй-жайлар үшін бізде бірқатар бір және екі килиллі дивандар бар, олар қонақ бөлмесінде аз орын алады және қажет болған жағдайда ыңғайлы бір немесе екі кереуетке айналады. Көп балалы отбасылар үшін біз үш қабатты диван-төсекті ұсына аламыз. Көптеген үйлерде, диван-төсектер қосалқы емес, негізгі кереует ретінде қолданылады. Бұл қонақ бөлмесінен түнгі бөлмеге айналатын студиялық пәтерлерге тән. Осылайша, диван-төсек - бұл ұзақ мерзімді жерде ақша үнемдейтін тұрақты инвестиция, өйткені сізге басқа ұйқыға арналған жиһазын сатып алудың қажеті жоқ.'
    },
    img: 'news-3.jpg'
  },
  {
    id: '4',
    date: '25.02.2024',
    ru: {
      title: 'Домашняя библиотека',
      shortDesc:
        'Есть проблемы с хранением в вашем домашнем офисе? Создайте дополнительные варианты хранения, необходимые вашему рабочему пространству, с помощью библиотечного шкафа. Зачастую, библиотечный шкаф, кроме открытых полок для хранения книг, имеет большие дверцы с деревянными фасадами, что придает ему дополнительный эффектный стиль.',
      fullDesc:
        'Есть проблемы с хранением в вашем домашнем офисе? Создайте дополнительные варианты хранения, необходимые вашему рабочему пространству, с помощью библиотечного шкафа. Зачастую, библиотечный шкаф, кроме открытых полок для хранения книг, имеет большие дверцы с деревянными фасадами, что придает ему дополнительный эффектный стиль. За дверями шкафа находится скрытое место для хранения с большой регулируемой полкой, которая может перемещаться на разную высоту, создавая гибкое хранилище для предметов всех форм и размеров. Место для хранения в нижнем шкафу идеально подходит для хранения стопок книг, папок, журналов и организации корзин. Верхняя поверхность закрытых полок  обеспечивает дополнительное пространство для таких предметов, как беспроводной принтер, декоративные растения или настольная лампа. Для удобства, библиотечный шкаф дополнительно снабжается металлической перекладиной со съёмной лестницей. Это позволит без труда достать необходимую вам книгу с самой верхней полки. Стильный библиотечный шкаф быстро наведет порядок в вашем кабинете или офисе, и организует рабочее пространство.'
    },
    en: {
      title: 'Home library',
      shortDesc:
        'Having storage problems in your home office? Create the extra storage options your workspace needs with a library cabinet. Often, a library cabinet, in addition to open shelves for storing books, has large doors with wooden fronts, which gives it an additional impressive style.',
      fullDesc:
        'Having storage problems in your home office? Create the extra storage options your workspace needs with a library cabinet. Often, a library cabinet, in addition to open shelves for storing books, has large doors with wooden fronts, which gives it an additional impressive style. Behind the cabinet doors is hidden storage space with a large adjustable shelf that can move to different heights, creating flexible storage for items of all shapes and sizes. Lower cabinet storage is ideal for storing stacks of books, folders, magazines and organizing baskets. The top surface of the enclosed shelves provides additional space for items such as a wireless printer, decorative plants or a table lamp. For convenience, the library cabinet is additionally equipped with a metal crossbar with a removable ladder. This will allow you to easily get the book you need from the top shelf. A stylish library cabinet will quickly bring order to your study or office and organize your workspace.'
    },
    kz: {
      title: 'Үй кітапханасы',
      shortDesc:
        'Сіздің үй кеңсеңізде сақтау проблемалары бар ма? Кітапхана шкафын қолдана отырып, жұмыс кеңістігіңізге қажетті қосымша сақтау параметрлерін жасаңыз. Көбінесе, кітапханалық жиһазы, кітаптарды сақтауға арналған сөрелерден басқа, ағаш қасбеттері бар үлкен есіктерімен жабдықталған, олар жиһазға қосымша керемет стиль береді.',
      fullDesc:
        'Сіздің үй кеңсеңізде сақтау проблемалары бар ма? Кітапхана шкафын қолдана отырып, жұмыс кеңістігіңізге қажетті қосымша сақтау параметрлерін жасаңыз. Көбінесе, кітапханалық жиһазы, кітаптарды сақтауға арналған сөрелерден басқа, ағаш қасбеттері бар үлкен есіктерімен жабдықталған, олар жиһазға қосымша керемет стиль береді. Шкафтың есігінен тыс жерде үлкен реттелетін сөре мен жасырын орын бар, бұл әр түрлі биіктіктерге ауысады. Ол барлық пішіндер мен өлшемдер үшін икемді сақтауды жасайды. Төменгі шкафта сақтау орны кітаптар, қалталар, журналдар және себеттерді ұйымдастыруға ыңғайлылық береді. Жабық сөрелердің үстіңгі беті сымсыз принтер, сәндік өсімдіктер немесе кесте шамы сияқты заттар үшін қосымша орын ұсынады. Қолайлылық үшін, кітапхана жиһазы қосымша алынбалы баспалдақ пен металл тіркесірмен қамталған. Бұл сізге ең жоғары сөрелерден қажет кітапты оңай алуға мүмкіндік береді. Стильді кітапхана шкафы сіздің кеңсеңізді реттеп, жұмыс кеңістігін ұйымдастыруға көмек береді.'
    },
    img: 'news-4.jpg'
  },
  {
    id: '5',
    date: '13.01.2024',
    ru: {
      title: 'Вазы в интерьере',
      shortDesc:
        'Украшение вазами - один из самых простых способов придать вашему дому непринуждённый стиль. С их помощью вы можете хвастаться свежими цветочными композициями, демонстрировать великолепные искусственные растения, или просто позволить вазе сиять самой по себе. Но, прежде чем вы начнёте украшать вазами, нужно выбрать стиль, который лучше всего подходит для вашего пространства.',
      fullDesc:
        'Украшение вазами - один из самых простых способов придать вашему дому непринуждённый стиль. С их помощью вы можете хвастаться свежими цветочными композициями, демонстрировать великолепные искусственные растения, или просто позволить вазе сиять самой по себе. Но, прежде чем вы начнёте украшать вазами, нужно выбрать стиль, который лучше всего подходит для вашего пространства. Если ваш дом а современном деревенском стиле, вы можете выбрать глиняные вазы или вазы из керамики. Для пространств с более гламурным дизайном попробуйте повесить квадратные настенные зеркала рядом с вазами из блестящих металлов, таких как серебро, золото или латунь. В комнату с минималистичным дизайном идеально впишется стеклянная ваза. Цвет вазы также может привнести в комнату особую атмосферу: для солнечного ощущения добавьте сосуд теплого цвета, например, глиняную вазу, в гостиную или кухню рядом с круглым настенным зеркалом. Для расслабленной атмосферы - вазы холодного оттенка. Теперь, когда вы определились с цветами и материалами, решите, как бы вы хотели оформить свои вазы. Можно наполнить большую вазу комнатными растениями. Вы также можете добавить цветы с одним стеблем, чтобы сделать минималистичный акцент, или полные цветущие букеты для свежей, органичной привлекательности. Разместите вазы там, где у вас есть свободная поверхность, которую можно было бы использовать в декоративных целях - они добавят индивидуальности приставным столикам, консольным столикам и книжным полкам. Или, если вы хотите сохранить простоту укладки, можете выбрать предварительно стилизованную композицию из нескольких цветов. Смешивайте и сочетайте современные вазы разных размеров и цветов, а затем добавляйте свежие или декоративные растения, чтобы создать привлекательные центральные элементы по всему дому.'
    },
    en: {
      title: 'Vases in the interior',
      shortDesc:
        'Decorating with vases is one of the easiest ways to add casual style to your home. With them, you can show off fresh floral arrangements, display gorgeous artificial plants, or simply let the vase shine on its own. But before you start decorating with vases, you need to choose the style that best suits your space.',
      fullDesc:
        'Decorating with vases is one of the easiest ways to add casual style to your home. With them, you can show off fresh floral arrangements, display gorgeous artificial plants, or simply let the vase shine on its own. But before you start decorating with vases, you need to choose the style that best suits your space. If your home has a modern rustic style, you can choose clay vases or ceramic vases. For spaces with a more glamorous design, try hanging square wall mirrors next to vases made of shiny metals such as silver, gold or brass. A glass vase will fit perfectly into a room with a minimalist design. The color of a vase can also add a special ambience to a room: for a sunny feel, add a warm-colored vessel, such as a clay vase, to your living room or kitchen next to a round wall mirror. For a relaxed atmosphere - vases in a cool shade. Now that you’ve decided on your colors and materials, decide how you’d like to style your vases. You can fill a large vase with indoor plants. You can also add single-stem flowers for a minimalist accent, or full bloom bouquets for a fresh, organic appeal. Place vases where you have free surface that could be used for decorative purposes - they will add character to side tables, console tables and bookshelves. Or, if you want to keep the styling simple, you can choose a pre-styled arrangement of multiple colors. Mix and match contemporary vases in different sizes and colors, then add fresh or decorative plants to create eye-catching centerpieces throughout the home.'
    },
    kz: {
      title: 'Интерьердегі вазалар',
      shortDesc:
        'Вазалармен безендіру - бұл сіздің үйіңізге жайлы стиль берудің қарапайым тәсілдерінің бірі. Олардың көмегімен сіз табиғи гүлдермен мақтана аласыз, керемет жасанды өсімдіктерді көрсете аласыз, немесе вазаның өздігінен жарқырап кетуіне мүмкіндік бере аласыз. Бірақ, вазалармен безендірмес бұрын, сіз өзіңіздің кеңістігіңізге қолайлы стильді таңдауыңыз керек.',
      fullDesc:
        'Вазалармен безендіру - бұл сіздің үйіңізге жайлы стиль берудің қарапайым тәсілдерінің бірі. Олардың көмегімен сіз табиғи гүлдермен мақтана аласыз, керемет жасанды өсімдіктерді көрсете аласыз, немесе вазаның өздігінен жарқырап кетуіне мүмкіндік бере аласыз. Бірақ, вазалармен безендірмес бұрын, сіз өзіңіздің кеңістігіңізге қолайлы стильді таңдауыңыз керек. Егер сіздің үйіңіз заманауи рустикалық стильде орындалған болса, сіз керамика немесе сазды вазаларды таңдай аласыз. Әдемі дизайны бар кеңістіктер үшін - күміс, алтын немесе жез жылтыр металдарынан жасалған вазалардың қасына қабырға айналарын іліп қоюға тырысыңыз. Шыны вазалары минималистік дизайнымен бөлмені жақсы үйлестіреді. Вазаның түсі де бөлмеге арнайы атмосфера әкелуі мүмкін. Күн сенсациясы үшін, қонақ бөлмесі, ас үйге  жарқын вазаларды қосыңыз. Немесе, тыныштық атмосферасы үшін - суық түстегі құмыраларды пайдаланыңыз. Енді, сіз гүлдер мен материалдар туралы шешім қабылдаған болсаңыз, сіздің құмыраларыңызды қалай ұйымдастырғыңыз келетінін шешіңіз. Үлкен вазаны табиғи өсімдіктермен толтыра аласыз. Сонымен қатар, минималистік екпін жасау үшін, бір тамыры бар гүлді қосуға болады, ал жаңа органикалық тартымдылық үшін - үлкен гүлденіп турған букетті пайдалануға болады. Сәндік мақсаттар үшін вазаларды пайдаланылатын бос бетті орналасқан жерге қойыңыз - олар консольді үстелдерге және кітап сөрелеріне жеке басын қосады. Егер сіз төсеудің қарапайымдылығын сақтағыңыз келсе, бірнеше түстерден стильденген гүл композициясын таңдай аласыз. Әр түрлі және әр түсті заманауи вазаларды біріктіруге тырысыңыз, олар үйде тартымды орталық элементтері болып қалады.'
    },
    img: 'news-5.jpg'
  },
  {
    id: '6',
    date: '10.12.2023',
    ru: {
      title: 'Мы открыли сезон!',
      shortDesc:
        'Ёлки и ёлочные игрушки уже в наличии! Приглашаем вас посетить наш салон, чтобы погрузиться в праздничную атмосферу и начать подготовку ко встрече Нового 2024 года! Этот год пройдёт под знаком зеленого деревянного дракона и это значит, что грядущий год будет одним из самых счастливых, ведь дракон - символ удачи, успеха и долгой радостной жизни!',
      fullDesc:
        'Ёлки и ёлочные игрушки уже в наличии! Приглашаем вас посетить наш салон, чтобы погрузиться в праздничную атмосферу и начать подготовку ко встрече Нового 2024 года! Этот год пройдёт под знаком зеленого деревянного дракона и это значит, что грядущий год будет одним из самых счастливых, ведь дракон - символ удачи, успеха и долгой радостной жизни! Самое главное в подготовке - выбор идеальной ёлки. Мы подготовили для вас разные модели - зелёных лесных красавиц и заснеженные ели, ёлки пристенные и ёлочки в горшках. Разбавить ваши елочные игрушки предлагаем нашими изысканными и стильными новогодними украшениями, которые идеально подходят для того, чтобы удивить ваших гостей и подарить всем лучшее начало Нового года. Посетив нашу галерею, ознакомьтесь с последними тенденциями в мире новогодних украшений, которые включают в себя ёлочные шары, гирлянды, рождественские венки, статуэтки и музыкальные шары, свечи и подсвечники, кольца для салфеток и подтарельники, и многое другое. Будь то для себя или в качестве подарков, они несомненно станут любимой частью будущих праздников. Встречайте Новый год стильно!'
    },
    en: {
      title: 'We have opened the season!',
      shortDesc:
        'Christmas trees and Christmas decorations are already in stock! We invite you to visit our salon to immerse yourself in the festive atmosphere and start preparing for the New Year 2024! This year will pass under the sign of the green wooden dragon and this means that the coming year will be one of the happiest, because the dragon is a symbol of good luck, success and a long, joyful life!',
      fullDesc:
        'Christmas trees and Christmas decorations are already in stock! We invite you to visit our salon to immerse yourself in the festive atmosphere and start preparing for the New Year 2024! This year will pass under the sign of the green wooden dragon and this means that the coming year will be one of the happiest, because the dragon is a symbol of good luck, success and a long, joyful life! The most important thing in preparation is choosing the perfect Christmas tree. We have prepared different models for you - green forest beauties and snow-covered spruce trees, wall-mounted trees and Christmas trees in pots. We offer to brighten up your Christmas tree decorations with our exquisite and stylish New Year’s decorations, which are ideal to surprise your guests and give everyone the best start to the New Year. By visiting our gallery, check out the latest trends in Christmas decorations, which include Christmas tree balls, garlands, Christmas wreaths, figurines and musical balls, candles and candle holders, napkin rings and placemats, and much more. Whether for yourself or as gifts, they are sure to become a favorite part of future holidays. Celebrate the New Year in style!'
    },
    kz: {
      title: 'Біз маусымды аштық!',
      shortDesc:
        'Шырша мен шырша ойыншықтары қазірдің өзінде біздің галереяда ұсынылған! Сіздерді біздің салонға мерекелік атмосфераға түсіп, жаңа 2024 жылды қарсы алуға дайындық жұмыстарын бастауға шақырамыз! Келе жатқан жыл жасыл ағаш айдаһардың белгісімен өтеді, сондықтан бұл жыл ең бақытты болады, өйткені, айдаһар сәттілікт, бақыт, ұзақ қүанышты өмірдің символы!',
      fullDesc:
        'Шырша мен шырша ойыншықтары қазірдің өзінде біздің галереяда ұсынылған! Сіздерді біздің салонға мерекелік атмосфераға түсіп, жаңа 2024 жылды қарсы алуға дайындық жұмыстарын бастауға шақырамыз! Келе жатқан жыл жасыл ағаш айдаһардың белгісімен өтеді, сондықтан бұл жыл ең бақытты болады, өйткені, айдаһар сәттілікт, бақыт, ұзақ қүанышты өмірдің символы! Дайындықтағы ең бастысы - мінсіз шыршаны таңдау. Біз сіздерге түрлі модельдерді ұсынамыз - жасыл орман сұлулары мен қарлы шыршаларды, қабырға алдына қойылатын шырша мен құмырадағы шыршаларды. Өз ойыншықтарыңызға біздің сәнді әрі стильді әшекейлерімізді қосыңыз, олар қонақтарыңызды таңдандырып, сізге Жаңа жылды жақсы бастауға мүмкіншілік береді. Бізге келіп әлемдегі жаңа жылдық бұйымдарының соңғы тенденцияларымен таңыс болыңыз. Соның ішінде шыршалар, шырша ойыншықтары, гирляндалар, рождестволық гүл шоқтары, мүсіншілер, шамдар мен тостағандар, майлық сақиналары мен табақ астырдағы тақталар және т.б. Өзіңізге ме, сыйлық ретінде ме, олар келе жатқан мерекенің сүйікті бөлігі бола алатыны ақиқат! Жаңа 2023 жылды стильді қарсы алыңыз!'
    },
    img: 'news-6.jpg'
  },
  {
    id: '7',
    date: '01.11.2023',
    ru: {
      title: 'Мне по фэншуй: как правильно сделать перестановку мебели в доме',
      shortDesc:
        '“В любой непонятной ситуации двигай мебель”, — смеется Александра Галкина, которая занимается фэншуй более десяти лет. Она поясняет: согласно этой древнекитайской практике, в каждом доме есть энергетически сильные точки. Они помогают реализовать планы и мечты. Соответственно, в противовес им существуют “слабые” зоны, где нельзя долго находиться.',
      fullDesc:
        '“В любой непонятной ситуации двигай мебель”, — смеется Александра Галкина, которая занимается фэншуй более десяти лет. Она поясняет: согласно этой древнекитайской практике, в каждом доме есть энергетически сильные точки. Они помогают реализовать планы и мечты. Соответственно, в противовес им существуют “слабые” зоны, где нельзя долго находиться. Важно, что каждый год “расклад” хороших и плохих направлений меняется — они не постоянны. И если любимый диван стоит в одном углу уже несколько лет, а в карьере и личной жизни, несмотря на усилия, ничего не происходит, возможно, пора сделать перестановку. По словам эксперта по фэншуй и блогера Анастасии Коротиной, дом не просто может, а должен “работать” на хозяев. Самое главное — правильное расположение мест, где проводят больше всего времени: письменного стола (особенно с учетом перехода многих на удаленку), кровати и плиты. Так, в следующем году ребенку учиться лучше в южном секторе комнаты: определяется он, как и другие, при помощи компаса. А вот взрослым кровать и рабочий стол следует разместить на западе или северо-востоке. Такая локация, по словам Коротиной, привлечет финансовое благополучие и вдохновение. Также хорошо, если дверь дома выходит на северо-восток или запад. “В первом случае вас ждет прорыв: новое дело или перемещение на новый уровень в карьере. Во втором — хороший заработок”, — считает астролог Дарья Высоцкая. Есть еще вариант: просто повесить на ручку двери колокольчик. “Его звук очистит пространство от отрицательных вибраций”, — объясняет Высоцкая.'
    },
    en: {
      title: 'Мне по фэншуй: как правильно сделать перестановку мебели в доме',
      shortDesc:
        '“В любой непонятной ситуации двигай мебель”, — смеется Александра Галкина, которая занимается фэншуй более десяти лет. Она поясняет: согласно этой древнекитайской практике, в каждом доме есть энергетически сильные точки. Они помогают реализовать планы и мечты. Соответственно, в противовес им существуют “слабые” зоны, где нельзя долго находиться.',
      fullDesc:
        '“В любой непонятной ситуации двигай мебель”, — смеется Александра Галкина, которая занимается фэншуй более десяти лет. Она поясняет: согласно этой древнекитайской практике, в каждом доме есть энергетически сильные точки. Они помогают реализовать планы и мечты. Соответственно, в противовес им существуют “слабые” зоны, где нельзя долго находиться. Важно, что каждый год “расклад” хороших и плохих направлений меняется — они не постоянны. И если любимый диван стоит в одном углу уже несколько лет, а в карьере и личной жизни, несмотря на усилия, ничего не происходит, возможно, пора сделать перестановку. По словам эксперта по фэншуй и блогера Анастасии Коротиной, дом не просто может, а должен “работать” на хозяев. Самое главное — правильное расположение мест, где проводят больше всего времени: письменного стола (особенно с учетом перехода многих на удаленку), кровати и плиты. Так, в следующем году ребенку учиться лучше в южном секторе комнаты: определяется он, как и другие, при помощи компаса. А вот взрослым кровать и рабочий стол следует разместить на западе или северо-востоке. Такая локация, по словам Коротиной, привлечет финансовое благополучие и вдохновение. Также хорошо, если дверь дома выходит на северо-восток или запад. “В первом случае вас ждет прорыв: новое дело или перемещение на новый уровень в карьере. Во втором — хороший заработок”, — считает астролог Дарья Высоцкая. Есть еще вариант: просто повесить на ручку двери колокольчик. “Его звук очистит пространство от отрицательных вибраций”, — объясняет Высоцкая.'
    },
    kz: {
      title: 'Мне по фэншуй: как правильно сделать перестановку мебели в доме',
      shortDesc:
        '“В любой непонятной ситуации двигай мебель”, — смеется Александра Галкина, которая занимается фэншуй более десяти лет. Она поясняет: согласно этой древнекитайской практике, в каждом доме есть энергетически сильные точки. Они помогают реализовать планы и мечты. Соответственно, в противовес им существуют “слабые” зоны, где нельзя долго находиться.',
      fullDesc:
        '“В любой непонятной ситуации двигай мебель”, — смеется Александра Галкина, которая занимается фэншуй более десяти лет. Она поясняет: согласно этой древнекитайской практике, в каждом доме есть энергетически сильные точки. Они помогают реализовать планы и мечты. Соответственно, в противовес им существуют “слабые” зоны, где нельзя долго находиться. Важно, что каждый год “расклад” хороших и плохих направлений меняется — они не постоянны. И если любимый диван стоит в одном углу уже несколько лет, а в карьере и личной жизни, несмотря на усилия, ничего не происходит, возможно, пора сделать перестановку. По словам эксперта по фэншуй и блогера Анастасии Коротиной, дом не просто может, а должен “работать” на хозяев. Самое главное — правильное расположение мест, где проводят больше всего времени: письменного стола (особенно с учетом перехода многих на удаленку), кровати и плиты. Так, в следующем году ребенку учиться лучше в южном секторе комнаты: определяется он, как и другие, при помощи компаса. А вот взрослым кровать и рабочий стол следует разместить на западе или северо-востоке. Такая локация, по словам Коротиной, привлечет финансовое благополучие и вдохновение. Также хорошо, если дверь дома выходит на северо-восток или запад. “В первом случае вас ждет прорыв: новое дело или перемещение на новый уровень в карьере. Во втором — хороший заработок”, — считает астролог Дарья Высоцкая. Есть еще вариант: просто повесить на ручку двери колокольчик. “Его звук очистит пространство от отрицательных вибраций”, — объясняет Высоцкая.'
    },
    img: 'news-7.jpg'
  },
  {
    id: '8',
    date: '01.11.2023',
    ru: {
      title: '«Сделано в Италии»',
      shortDesc:
        'Прозрачность, светимость, звучность - прилагательные, отличающие продукцию IVV, не имеющую себе равных в мире. Доказательством этого является то, что любому, кто пытался подражать её продукции, так и не удалось достичь его качества.',
      fullDesc:
        'Прозрачность, светимость, звучность - прилагательные, отличающие продукцию IVV, не имеющую себе равных в мире. Доказательством этого является то, что любому, кто пытался подражать её продукции, так и не удалось достичь его качества. IVV Industria Vetraria Valdarnese был основан в 1952 году в Сан-Джованни-Вальдарро, в самом центре Тосканы, группой мастеров по стеклу. И они являются одними из немногих производителей стекла, которые до сих пор производят продукцию в Италии. За более чем 60 лет своего существования IVV зарекомендовал себя среди европейских лидеров производства выдувного стекла ручной работы, сочетая исследования материалов, дизайна, методов традиционного мастерства и управления процессом. Компания смогла сохранить ремесленную составляющую производства своего стекла неизменной. Продукция IVV - это изделия с декоративной жилкой: коллекции ваз для фруктов, салатницы, менажницы, этажерки, кувшины и бокалы и многое другое. Характеризуются способом изготовления стекла с более или менее ярковыраженной, но всегда присутствующей текстурой - узорчатой, скошенной, с полным или частичным добавлением цвета. Независимо от того, что вы подаёте, эти изделия станут элегантным дополнением к любому столу, прекрасно оттенят традиционную сервировку и придадут ей особый шарм и оригинальность.'
    },
    en: {
      title: '«Made in Italy»',
      shortDesc:
        'Transparency, luminosity, sonority are adjectives that distinguish IVV products, which have no equal in the world. The proof of this is that anyone who has tried to imitate its products has never been able to match its quality.',
      fullDesc:
        'Transparency, luminosity, sonority are adjectives that distinguish IVV products, which have no equal in the world. The proof of this is that anyone who has tried to imitate its products has never been able to match its quality. IVV Industria Vetraria Valdarnese was founded in 1952 in San Giovanni Valdarro, in the heart of Tuscany, by a group of glass artisans. And they are one of the few glass manufacturers that still manufacture in Italy. In its more than 60 years of existence, IVV has established itself among Europe’s leaders in hand-blown glass production, combining research into materials, design, traditional craftsmanship and process control. The company was able to keep the artisanal aspect of its glass production intact. IVV products are products with a decorative vein: collections of fruit vases, salad bowls, display racks, shelves, jugs and glasses and much more. They are characterized by a method of producing glass with a more or less pronounced, but always present texture - patterned, beveled, with full or partial addition of color. Regardless of what you serve, these products will be an elegant addition to any table, perfectly complementing traditional table settings and giving it a special charm and originality.'
    },
    kz: {
      title: '«Италияда жасалған»',
      shortDesc:
        'Мөлдірлік, жарықтық, дыбыстық – әлемде теңдесі жоқ IVV өнімдерін ерекшелейтін сын есімдері. Дәлелі, осы өнімдеріне еліктеуге тырысқан кез келген өндірүші оның сапасына ешқашан тең келе алмаған.',
      fullDesc:
        'Мөлдірлік, жарықтық, дыбыстық – әлемде теңдесі жоқ IVV өнімдерін ерекшелейтін сын есімдері. Дәлелі, осы өнімдеріне еліктеуге тырысқан кез келген өндірүші оның сапасына ешқашан тең келе алмаған. IVV Industria Vetraria Valdarnese 1952 жылы Сан-Джованни Вальдаррода, Тоскананың қақ ортасында, шыны шеберлері тобымен құрылған. Және ол Италияда әлі күнге дейін өнім шығаратын бірнеше шыны өндірушілердің бірі. IVV өзінің 60 жылдан астам қызмет ету мерзімінде материалдар, дизайн, дәстүрлі шеберлік және процестерді басқару саласындағы зерттеулерді біріктіре отырып, қолмен үрлеу шыныдағы еуропалық көшбасшылар арасында өзін көрсетті. Компания шыны өндірісінің қолөнер құрамдас бөлігін өзгеріссіз сақтай алды. IVV өнімдері сәндік тамыры бар өнімдер болып табылады: жеміс-жидек вазаларының коллекциялары, салат табақтары, шыныаяқ ұстағыштар, бөтелкелер, құмыралар мен стақандар және т.б. Олар азды-көпті айқын көрінетін, бірақ әрқашан ұсынылатын текстурасы бар - өрнекті, қиғаш - толық немесе жартылай түсті қосу арқылы шыны жасау әдісімен сипатталады. Қандай қызмет көрсететініңізге қарамастан, бұл өнімдер кез келген дастарханға талғампаз қосымша болады, дәстүрлі жайылған дастарқанды тамаша үйлестіреді, және оған ерекше сүйкімділік пен ерекшелік береді.'
    },
    img: 'news-8.jpg'
  }
]
